language: python

python:
    - 3.6

os: osx

install:
    - pip install -r requirements.txt

script:
    - pytest

env:
    - WITH_JASPER=ON BUILD_JASPER=OFF OPENCV_IO_ENABLE_JASPER=ON
    - BUILD_JASPER=ON WITH_JASPER=ON OPENCV_IO_ENABLE_JASPER=ON
    - eric=eric